### ISSUE TITLE
problems while training with dataset

### ISSUE THREAD

**Issue by snoopypi** [dasmehdix/drone-dataset#1]
Hey
Thanks for your dataset.
Unfortunately I have some issues..
I am working with tensorflow and took your Images as dataset.

When I want to try the model I get the following error:

```
flu@flubuntu:~/Tensorflow/scripts/preprocessing$ python3 generate_tfrecord.py --label=drone --csv_input=/home/flu/Tensorflow/workspace/training_demo/annotations/test_labels.csv --img_path=/home/flu/Tensorflow/workspace/training_demo/images/test --output_path=/home/flu/Tensorflow/workspace/training_demo/annotations/test.record
/home/flu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/flu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/flu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/flu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/flu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/flu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "generate_tfrecord.py", line 117, in <module>
    tf.app.run()
  File "/home/flu/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 108, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 64, in create_tf_example
    image = Image.open(encoded_jpg_io)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2590, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7fb7f8d869e8>
```

Can you help me with that?

Thx so much

**Comment by dasmehdix** [comment]
First of all, please read [this](https://github.com/dasmehdix/drone-dataset/blob/master/README.md).
- Did you covert all images to `*jpg` format?
- Which version pillow you use?
- Check [this too](https://stackoverflow.com/questions/19230991/image-open-cannot-identify-image-file-python)
- I think your problem occurs beacuse of the pillow library in your pc and please star if you use my dataset :)
- Also, this error can be occur if a image file is corupted.I checked dataset and it seems that the images in dataset looks work well.I can train this dataset.

**Comment by snoopypi** [comment]
Hi thank you for your response.

- I have pillow 6.2.1

- Yes I converted all to jpg.

- My error first was that some of the xml. files still use the png. format. 
For example: <filename>yoto10818.png</filename>

Then an error occured which said could not find the yoto10818.png. (because I converted them to jpg)

Then I searched for all png in the xml. files and replaced it with jpg.
And then the error in my first post occured.

- I gave you a star anyway :)

-  I read the BONUS1 but not sure how to use this xml.parser to solve the path problem.

**Comment by dasmehdix** [comment]
> Hi thank you for your response.
> 
> * I have pillow 6.2.1
> * Yes I converted all to jpg.
> * My error first was that some of the xml. files still use the png. format.
>   For example: yoto10818.png
> 
> Then an error occured which said could not find the yoto10818.png. (because I converted them to jpg)
> 
> Then I searched for all png in the xml. files and replaced it with jpg.
> And then the error in my first post occured.
> 
> * I gave you a star anyway :)
> * I read the BONUS1 but not sure how to use this xml.parser to solve the path problem.

- My pillow version is 6.1.0
- Hmm, I suggest you to use xmlparser.It written in Javascript language and change the path in the xml files for custom usage.You have to change [this](https://github.com/dasmehdix/drone-dataset/blob/3ae6e3392abd9fc6fb4f61a9fccc694aeee484b3/xmlparser/index.js#L4) path(4th and 5th row) inplace of xml files in your path.Then run this script and it will change the path inside xml files correctly.Be sure that xml files has to be in correct path.
- xmlparser, basicly, enter the path that you gave and look for all xml files in the path in order.Then script enter inside the xml file one by one and change the path in the xml file with the new one and it change the image format to jpg(if not jpg).Then it save the xml file.
- Also, you can label it yourself which is more exhausting but easy.I used [labelimg](https://github.com/tzutalin/labelImg) to label images.
- Thanks for your star, you can upvote in kaggle too :))))
