### ISSUE TITLE
A question about Dataset

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [dasmehdix/drone-dataset#2]
Hi there, 
              Thanks for the dataset.  I have downloaded dataset from https://www.kaggle.com/dasmehdixtr/drone-dataset-uav

There are two sets, one is xml format and other is txt format. My question is: Are the pictures are same in both sets or different?

**Comment by dasmehdix** [comment]
The "txt" dataset contains 250 more images than"xml" one, but in accuracy performance there are not diffrence between datasets.

**Comment by MuhammadAsadJaved** [comment]
OK. got it. Thanks
